<?php

// All emmissions factors in tonnes of CO2 per X

define( 'CREF_GAS',  0.22554/1000);
define( 'CREF_ELEC',  0.61707/1000);

define( 'CREF_CAR_PS', 0.20499/1000);
define( 'CREF_CAR_PM', 0.25436/1000);
define( 'CREF_CAR_PL', 0.35396/1000);
define( 'CREF_CAR_PU', 0.24947/1000);
define( 'CREF_CAR_DS', 0.17474/1000);
define( 'CREF_CAR_DM', 0.21740/1000);
define( 'CREF_CAR_DL', 0.29426/1000);
define( 'CREF_CAR_DU', 0.23406/1000);
define( 'CREF_CAR_HA', 0.19520/1000);

define( 'CREF_FLIGHT_DOM_LIMIT', 785.5); // in km
define( 'CREF_FLIGHT_MED_LIMIT', 3700); // in km


define( 'CREF_FLIGHT_DOM',  0.389785/1000);
define( 'CREF_FLIGHT_MED',  0.210026/1000);
define( 'CREF_FLIGHT_LONG', 0.257165/1000);

?>